### ISSUE TITLE
package.elm-lang.org is not reachable from Russia

### ISSUE THREAD

**Issue by nikita-volkov** [elm/package.elm-lang.org#308] opened 2019-06-22 17:48 UTC
The IP of the webserver must have somehow gotten blacklisted on the federal level, so the only way of reaching the service from Russia is through VPN. Please consider changing the IP.

**Comment by Razzeee** [comment] 2019-06-22 22:06
Duplicate of https://github.com/elm/package.elm-lang.org/issues/300 and https://github.com/elm/package.elm-lang.org/issues/278

**Closed** 2019-06-23 11:10 UTC
